#Requires -Version 7.0
<#
.SYNOPSIS
    SMSDAO Platform — PR Comment Resolver
.DESCRIPTION
    Builds, posts, and resolves GitHub PR comments.
    All comment bodies are generated by New-CommentBody — never
    constructed inline in phase modules (DRY).
    Finds stale bot comments and replaces them atomically so the
    PR thread stays clean regardless of run count.
#>

using module ../utils/logger.psm1

$BOT_TAG = "<!-- smsdao-pipeline-bot -->"

# ── Comment body factory ─────────────────────────────────────────
function New-CommentBody {
    <#
    .SYNOPSIS
        Generate a rich Markdown comment body for any pipeline event.
    .PARAMETER EventType
        phase_start | phase_success | phase_failure | heal_action |
        config_loaded | repo_detected | env_validated | dry_run | security_alert
    #>
    param(
        [Parameter(Mandatory=$true)]
        [ValidateSet(
            "phase_start","phase_success","phase_failure",
            "heal_action","config_loaded","repo_detected",
            "env_validated","dry_run","security_alert"
        )]
        [string]$EventType,

        [Parameter(Mandatory=$true)]
        [string]$PhaseLabel,

        [string]$Env          = "Dev",
        [string]$Repo         = "",
        [string]$Detail       = "",
        [hashtable]$Metadata  = @{},
        [hashtable]$CustomArgs= @{},
        [bool]$IsDryRun       = $false
    )

    $timestamp = (Get-Date -Format "yyyy-MM-dd HH:mm:ss") + " UTC"
    $runUrl    = if ($env:GITHUB_RUN_ID -and $Repo) {
        "[$($env:GITHUB_RUN_NUMBER)](https://github.com/$Repo/actions/runs/$($env:GITHUB_RUN_ID))"
    } else { "local" }

    $iconMap = @{
        phase_start    = @{ icon = ":hourglass_flowing_sand:"; badge = "![Running](https://img.shields.io/badge/status-running-blue)";  title = "Running"       }
        phase_success  = @{ icon = ":white_check_mark:";        badge = "![Passed](https://img.shields.io/badge/status-passed-brightgreen)"; title = "Succeeded" }
        phase_failure  = @{ icon = ":x:";                       badge = "![Failed](https://img.shields.io/badge/status-failed-red)";    title = "Failed"        }
        heal_action    = @{ icon = ":adhesive_bandage:";         badge = "![Healing](https://img.shields.io/badge/status-healing-orange)"; title = "Healing"     }
        config_loaded  = @{ icon = ":page_facing_up:";           badge = "![Config](https://img.shields.io/badge/config-loaded-blue)";  title = "Config Loaded" }
        repo_detected  = @{ icon = ":mag:";                      badge = "![Detected](https://img.shields.io/badge/repo-detected-blue)"; title = "Detected"     }
        env_validated  = @{ icon = ":shield:";                   badge = "![Valid](https://img.shields.io/badge/env-valid-brightgreen)"; title = "Validated"    }
        dry_run        = @{ icon = ":test_tube:";                badge = "![Dry Run](https://img.shields.io/badge/mode-dry--run-purple)"; title = "Dry Run"     }
        security_alert = @{ icon = ":rotating_light:";           badge = "![Alert](https://img.shields.io/badge/security-alert-red)";  title = "Security Alert" }
    }

    $m     = $iconMap[$EventType]
    $icon  = $m.icon
    $badge = $m.badge
    $title = $m.title

    # Core table rows
    $coreRows = @(
        "| Phase | ``$PhaseLabel`` |"
        "| Status | **$title** $badge |"
        "| Environment | ``$Env`` |"
        "| Run | $runUrl |"
        "| Timestamp | $timestamp |"
    )
    if ($IsDryRun) { $coreRows += "| Mode | ``DRY RUN — nothing executed`` |" }
    if ($Detail)   { $coreRows += "| Detail | $Detail |" }

    # Extra metadata rows
    $metaRows = $Metadata.GetEnumerator() | Sort-Object Key |
                ForEach-Object { "| $($_.Key) | ``$($_.Value)`` |" }

    # CustomArgs block — secrets masked
    $safeArgs = $CustomArgs.GetEnumerator() | Sort-Object Key | ForEach-Object {
        $v = if ($_.Key -match '(?i)(secret|token|pass|key|pwd|cred|auth)') { '`***(masked)**`' } else { $_.Value }
        "| ``$($_.Key)`` | $v |"
    }

    $argsSection = if ($safeArgs) { @"

<details>
<summary><strong>⚙️ Runtime Args</strong></summary>

| Key | Value |
|---|---|
$($safeArgs -join "`n")

</details>
"@ } else { "" }

    $allRows = ($coreRows + $metaRows) -join "`n"

    return @"
$BOT_TAG
---
### $icon SMSDAO Pipeline — **$PhaseLabel** · ``$Env``

| Field | Value |
|---|---|
$allRows
$argsSection

> *Powered by [SMSDAO/platform](https://github.com/SMSDAO/platform)*
"@
}

# ── Resolver — find, delete stale, post fresh ────────────────────
function Invoke-PRComment {
    <#
    .SYNOPSIS
        Post or replace a bot comment on a GitHub PR.
    .PARAMETER EventType
        Maps to an icon/badge/title in New-CommentBody.
    .PARAMETER PhaseLabel
        Human-readable phase name shown in the comment header.
    #>
    param(
        [Parameter(Mandatory=$true)]
        [string]$EventType,

        [Parameter(Mandatory=$true)]
        [string]$PhaseLabel,

        [string]$Env          = "Dev",
        [string]$Token        = $env:GH_TOKEN,
        [string]$Repo         = $env:GITHUB_REPOSITORY,
        [string]$PR           = $env:PR_NUMBER,
        [string]$Detail       = "",
        [hashtable]$Metadata  = @{},
        [hashtable]$CustomArgs= @{},
        [bool]$IsDryRun       = $false
    )

    if (-not $PR -or -not $Token -or -not $Repo) {
        Write-Info "PR comment skipped (PR_NUMBER / GH_TOKEN / GITHUB_REPOSITORY not set)."
        return
    }

    $body    = New-CommentBody -EventType $EventType -PhaseLabel $PhaseLabel `
                               -Env $Env -Repo $Repo -Detail $Detail `
                               -Metadata $Metadata -CustomArgs $CustomArgs -IsDryRun $IsDryRun
    $headers = @{
        Authorization          = "Bearer $Token"
        Accept                 = "application/vnd.github+json"
        "X-GitHub-Api-Version" = "2022-11-28"
    }
    $listUrl = "https://api.github.com/repos/$Repo/issues/$PR/comments"

    try {
        # 1. Page through comments — find stale bot entry
        $existing = $null; $page = 1
        do {
            $resp  = Invoke-RestMethod -Uri "$listUrl`?per_page=100&page=$page" `
                                       -Headers $headers -Method GET -ErrorAction Stop
            $match = $resp | Where-Object { $_.body -like "*$BOT_TAG*" } | Select-Object -First 1
            if ($match) { $existing = $match; break }
            $page++
        } while ($resp.Count -eq 100)

        # 2. Delete stale comment (resolve thread)
        if ($existing) {
            Write-Info "Resolving stale bot comment #$($existing.id)..."
            if (-not $IsDryRun) {
                Invoke-RestMethod `
                    -Uri "https://api.github.com/repos/$Repo/issues/comments/$($existing.id)" `
                    -Headers $headers -Method DELETE -ErrorAction Stop | Out-Null
            } else {
                Write-Dry "Would delete PR comment #$($existing.id)"
            }
        }

        # 3. Post fresh comment
        if (-not $IsDryRun) {
            $payload = @{ body = $body } | ConvertTo-Json -Depth 5
            $posted  = Invoke-RestMethod -Uri $listUrl -Headers $headers `
                                         -Method POST -Body $payload `
                                         -ContentType "application/json" -ErrorAction Stop
            Write-Info "PR comment posted -> $($posted.html_url)"
        } else {
            Write-Dry "Would post comment [$EventType] on PR #$PR"
        }
    }
    catch {
        # Non-fatal — comment failure must never stop the pipeline
        Write-Warn "PR comment warning: $_"
    }
}

Export-ModuleMember -Function New-CommentBody, Invoke-PRComment -Variable BOT_TAG
